name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: gofmt
        if: runner.os == 'Linux'
        shell: bash
        run: test -z "$(gofmt -l .)"

      - name: go vet
        run: go vet ./...

      - name: go test (race)
        if: runner.os == 'Linux'
        run: go test -race ./...

      - name: go test
        if: runner.os != 'Linux'
        run: go test ./...

  cross:
    name: cross (${{ matrix.goos }}/${{ matrix.goarch }}${{ matrix.goarm }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: windows
            goarch: amd64
            goarm: ""
            pkg: ./cmd/yab
          - goos: linux
            goarch: arm64
            goarm: ""
            pkg: ./cmd/yabd
          - goos: linux
            goarch: arm
            goarm: "7"
            pkg: ./cmd/yabd
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Cross build
        env:
          CGO_ENABLED: "0"
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: go build ${{ matrix.pkg }}

      - name: Cross vet
        env:
          CGO_ENABLED: "0"
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: go vet ./...
